name: Publish

on:
  workflow_run:
    workflows: ["Lint and Test"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - name: Install deps and build
      run: |
        set -e
        npm ci
        npm run build
    - name: Publish to npm
      run: npm publish --tag latest --access public --provenance
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
